### ISSUE TITLE
Ошибка в тесте [success] OAuth2 Resource Owner flow

### ISSUE THREAD

**Issue by mshat** [bmstu-rsoi/lab5-template#1]
В проверяющем скрипте переменная authorizationToken инициализируется неправильно:
pm.collectionVariables.set(\"authorizationToken\", **request**.access_token)",

Должно быть:  
pm.collectionVariables.set(\"authorizationToken\", **response**.access_token)",

Ошибка присутствует вот всех вариантах.
![image](https://user-images.githubusercontent.com/37267798/149014965-0f7f309b-b8a3-4d00-80af-ebfaaeb0ed65.png)

**Comment by LuckySting** [comment]
Тоже заметил, вот ПР на это https://github.com/bmstu-rsoi/lab5-template/pull/2

**Comment by Romanow** [comment]
Исправлено в [PR #2](https://github.com/bmstu-rsoi/lab5-template/issues/2)
